# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
sudo: false
cache: packages

env:
  global:
  - secure: "dHknlaJtXultVqPvFRce3BdBa6gxgFNvaqN1k9rd0PAVSThOhKxPjQ9IYiINgYujtTCJXWFPKyyG76OoTlWfRsbV+XDieWu9TqQk96yTc8wi4p93RffsYJypg7qhy8lGc2rDqwge0f48v6IB0g6pIsHjWz6pq7nW+OBSUFvBGV4="

install:
  - R -e 'install.packages(c("devtools", "roxygen2"))'
  - R -e 'devtools::install_deps(dep = T)'
  - R -e 'devtools::document()'
  - R -e 'devtools::install()'

after_success:
  - GH_REPO="@github.com/rmflight/trackWeight.git"
  - FULL_REPO="https://$GH_TOKEN$GH_REPO"
  - R -e 'rmarkdown::render("README.Rmd")'
  - git config user.name "rmflight-travis"
  - git config user.email "travis"
  - git add README.md
  - git commit -m 'added data point'
  - git push $FULL_REPO master
